# iModel.js CI Build

trigger:
  - master
  - release/*

jobs:
  - template: ci-core.yaml
    parameters:
      name: Node_12
      nodeVersion: 14.x
      pool:
        demands:
        - Agent.OS -equals $(platform)

