# iModel.js CI Build

trigger:
  - master
  - release/*

pr:
  drafts: false
  branches:
    include:
    - master
    - releases/*

jobs:
  - template: ci-core.yaml
    parameters:
      name: Node_14
      nodeVersion: 14.x
      pool:
        demands:
        - Agent.OS -equals $(platform)

