# iModel.js CI Build

trigger:
  - master
  - release/*

pr:
  drafts: false
  branches:
    include:
      - master
      - releases/*

jobs:
  - template: ci-core.yaml
    parameters:
      name: Node_12
      nodeVersion: 12.x
      pool:
        demands:
          - Agent.OS -equals $(platform)
