# iModel.js CI Build

trigger:
  schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
      - master
      - releases/*
  pr:
    branches:
      include:
      - master
      - releases/*
    paths:
      include:
      - common/config/azure-pipelines/ci.yaml

jobs:
  - template: jobs/ci-core.yaml
    parameters:
      name: Node_14
      nodeVersion: 14.x
      pool:
        vmImage: $(OS)
